# Use an Ubuntu base image
FROM ubuntu:22.04

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Update package lists and install required dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common \
    python3-apt \
    ca-certificates \
    curl \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    libffi-dev \
    libgdbm-dev \
    wget \
    lsb-release \
    apt-transport-https \
    gnupg \
    systemd \
    && apt-get clean

# Add the deadsnakes PPA, which contains Python 3.12
RUN add-apt-repository ppa:deadsnakes/ppa && apt-get update

# Install Python 3.12 slim version
RUN apt-get install -y --no-install-recommends python3.12 python3.12-venv python3.12-dev python3.12-distutils

# Set Python 3.12 as the default version of Python
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1

# Install pip for Python 3.12
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py && rm get-pip.py

# Installing ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

COPY ./start.sh /start.sh
RUN chmod +x /start.sh

CMD ["/start.sh"]

